FE-217 - Add principal physician section
francodimasi/uepm-front-react pull request #148
Opened 2024-03-19 16:27 UTC by lsmartinez88

# Description

We need to add a new section in the site detail page for the principal physician of a site study. This section could present more than one physician. We are waiting for designers to define how we will show the data on each scenario.

# Jira tickets

Please include a list with the tickets involved in this pull request :pray:

- [FE-217| Add principal physician section](https://trialtech.atlassian.net/browse/FE-217)

# Screenshots

![image](https://github.com/francodimasi/uepm-front-react/assets/13772882/5fecb398-aad6-4512-ae12-75d832f7685f)

![image](https://github.com/francodimasi/uepm-front-react/assets/13772882/3ae579aa-bab6-4f0a-9731-8d84e61a1455)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue) :bug:
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) :bomb::boom:
- [ ] Configuration / Setup :wrench:
- [ ] Clean up / Technical debt :hammer:

## Apps affected by this change

- [x] Web
- [ ] Landing
- [ ] Management portal

## Project code modified by this change

- [x] Web
- [ ] Landing
- [ ] Management portal
- [ ] Packages

# Checklist:

- [x] I have performed a self-review of my own code :innocent:
- [x] My code is clean and it follows the guidelines of this project :nail_care:
- [x] My changes don't generate new warnings :ok_hand:

2024-03-19 20:48 UTC, libattistella requested changes

2024-03-19 20:48 UTC, libattistella commented on apps/web/app/[lang]/sites/[id]/page.tsx
> +                            <p className="text-primary-dark text-sm md:text-base font-normal font-['DMSans'] uppercase leading-tight">
We can use a Typography here, maybe P2?

2024-03-19 20:48 UTC, libattistella commented on apps/web/app/[lang]/sites/[id]/page.tsx
> +                            <p className="text-primary text-xl md:text-2xl font-semibold font-['Lexend'] leading-7">{`${py.first_name} ${py.last_name}`}</p>
Same here

2024-03-19 20:48 UTC, libattistella commented on apps/web/app/[lang]/sites/[id]/page.tsx
> +                            {py.description}
Same

2024-03-20 01:48 UTC, lsmartinez88 commented
Pr changes applied @libattistella

2024-03-20 13:42 UTC, libattistella approved these changes

2024-03-20 13:49 UTC, merged