FE-226 Study detail side card
francodimasi/uepm-front-react pull request #158
Opened 2024-04-05 19:14 UTC by jbianciotto

# Description

Study detail side card

# Jira tickets

https://trialtech.atlassian.net/browse/FE-226

# Screenshots

![Screenshot from 2024-04-05 16-13-49](https://github.com/francodimasi/uepm-front-react/assets/1674845/ef57a69f-7038-47cd-a1d0-c2ab43586181)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue) :bug:
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) :bomb::boom:
- [ ] Configuration / Setup :wrench:
- [ ] Clean up / Technical debt :hammer:

## Apps affected by this change

- [x] Web
- [ ] Landing
- [ ] Management portal

## Project code modified by this change

- [x] Web
- [ ] Landing
- [ ] Management portal
- [ ] Packages

# Checklist:

- [x] I have performed a self-review of my own code :innocent:
- [x] My code is clean and it follows the guidelines of this project :nail_care:
- [x] My changes don't generate new warnings :ok_hand:

2024-04-08 07:40 UTC, libattistella requested changes
Good job. A few things:

- Respect figma internal paddings for the card
- Respect figma gap between sections
- The dividers have 2px and should have 1px according figma

Also, please stop using `bg-white` or any other className with `white`, use `light` instead. If we ever have dark mode, we will have an easier job, plus we have the same backgroung across all components.

Finally, how are we showing this in **mobile**?

2024-04-08 07:40 UTC, libattistella commented on apps/web/app/[lang]/studies/[id]/page.tsx
> +        <div className="hidden col-span-1 lg:row-span-2 p-4 sm:flex flex-col">
Please remove padding, is not present in figma

2024-04-08 07:40 UTC, libattistella commented on apps/web/intl/locales/en.json
> +        "from": "From",
Same as I mentioned to @lsmartinez88 

We must identify common terms like "from", "to", "up to", etc, and put them inside `commonTerms` section. We must avoid to have a term like that repeated multiple times. Please move those to `commonTerms` along with the already defined terms for `age`.

2024-04-08 07:40 UTC, libattistella commented on packages/ui/core/divider/HorizontalDivider.tsx
Please remove this entire component, a divider shouldn't be more than a style or a class utility.

2024-04-08 07:40 UTC, libattistella commented on apps/web/app/[lang]/studies/[id]/components/StudyPreviewContent.tsx
> +    <Card className="w-full max-h-min flex flex-col items-center justify-center !m-0 !p-4 gap-6">
```suggestion
    <Card className="w-full flex flex-col justify-center !m-0 !p-4 gap-6">
```

Remove unneeded classes

2024-04-08 07:40 UTC, libattistella commented on apps/web/app/[lang]/studies/[id]/components/StudyPreviewContent.tsx
> +      <div className="w-full flex flex-col gap-4">
```suggestion
      <div className="flex flex-col gap-4">
```

If the parent is w-full and flex, and the children is also flex, the default width will be 100% already

2024-04-08 14:32 UTC, jbianciotto commented on apps/web/app/[lang]/studies/[id]/page.tsx
> +        <div className="hidden col-span-1 lg:row-span-2 p-4 sm:flex flex-col">
![image](https://github.com/francodimasi/uepm-front-react/assets/1674845/21b604a3-e929-4d00-b1cb-56481fea4174)
Figma looks like it has padding to me, I decided to use 16px instead of 24px because I  thought it was too big.
Where is the no padding specified?

2024-04-08 14:48 UTC, jbianciotto commented on packages/ui/core/divider/HorizontalDivider.tsx
I tried and googled several ways to achieve the horizontal divider in a flex container, and it is not as trivial as one would believe, specially having to maintain an equal padding around the divider.
I wont spend more time trying to engineer a combination of css classes or elements to achieve the same that this small, simple, clear and ease to use component does.

2024-04-08 15:03 UTC, jbianciotto commented on apps/web/app/[lang]/studies/[id]/components/StudyPreviewContent.tsx
> +      <div className="w-full flex flex-col gap-4">
Removing the w-full class makes content not fill all the container. I think it is related to the sibling button element also specifying full width, forcing the parent div to be wider than this div.  
However, also removing w-full from button makes it shrink to fit-content, so I think there is no way around setting both to w-full so they completely fill the parent grid cell

2024-04-08 15:25 UTC, jbianciotto commented
Mobile looks the same, but in a Modal. It is not clear to me from where it will be reached, but should be as simple as  <Modal> <SitePreviewContent/> </Modal> 
![image](https://github.com/francodimasi/uepm-front-react/assets/1674845/b9180445-a23f-4cb3-9b89-80fdae8db02e)
I think it should be handled in another story (possibly consisting on creating the calling page), as the component will be ready from this one

2024-04-08 15:37 UTC, libattistella commented on apps/web/app/[lang]/studies/[id]/page.tsx
> +        <div className="hidden col-span-1 lg:row-span-2 p-4 sm:flex flex-col">
Mi bad, I meant margin, not padding @jbianciotto

2024-04-09 17:32 UTC, libattistella approved these changes

2024-04-09 17:52 UTC, merged