FE-236 Typeform component
francodimasi/uepm-front-react pull request #167
Opened 2024-04-15 16:11 UTC by jbianciotto

# Description

Add a new Typeform component in /packages to embed or display a typeform in a modal.
Add support for reading form and country id query params to obtain the id of the typeform form 

# Jira tickets

https://trialtech.atlassian.net/browse/FE-236
https://trialtech.atlassian.net/browse/FE-240

# Screenshots

![image](https://github.com/francodimasi/uepm-front-react/assets/1674845/7475c135-c435-422f-b28f-16e0eb6b973d)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue) :bug:
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) :bomb::boom:
- [ ] Configuration / Setup :wrench:
- [ ] Clean up / Technical debt :hammer:

## Apps affected by this change

- [x] Web
- [ ] Landing
- [ ] Management portal

## Project code modified by this change

- [X] Web
- [ ] Landing
- [ ] Management portal
- [X] Packages

# Checklist:

- [X] I have performed a self-review of my own code :innocent:
- [X] My code is clean and it follows the guidelines of this project :nail_care:
- [X] My changes don't generate new warnings :ok_hand:

2024-04-16 12:08 UTC, libattistella requested changes
Nice!

2024-04-16 12:08 UTC, libattistella commented on packages/ui/components/typeform/typeform.types.ts
> +    hidden?: any;
```suggestion
    hidden?: {[key: string]: any};
```

2024-04-16 12:08 UTC, libattistella commented on apps/web/package.json
> +    "query-string": "^9.0.0",
Remove this and the install it in `packages/utils` and add a `getQueryString` function to a new file `packages/utils/strings.ts`. Then use that function from utils in the web project

2024-04-16 12:08 UTC, libattistella commented on apps/web/app/[lang]/studies/[id]/helpers.ts
> +import queryString from 'query-string';
Remove, you should import the utils function here

2024-04-17 16:14 UTC, libattistella requested changes
The component is not responding in mobile. It can't be closed neither start the journey

2024-04-17 16:14 UTC, libattistella commented on apps/web/app/[lang]/studies/[id]/helpers.ts
> +
This is overriding the previous if statement which is suppose to have preference. 

Apply this change please, I already checked that works fine. Replace this code 

```
  if (campaignId) {
    form = study.forms.find((form) => form.id === campaignId);
  }
  if (countryId) {
    form = study.forms.find((form) => form.country_id === countryId);
  } else {
    return {};
  }
```
with
 ```
  if (!campaignId?.length && !countryId?.length) return {};

  if (campaignId) {
    form = study.forms.find((form) => form.id === campaignId);
  } else {
    form = study.forms.find((form) => form.country_id === countryId);
  }
```

2024-04-17 16:14 UTC, libattistella commented on apps/web/app/[lang]/studies/[id]/helpers.ts
> +
We are not checking if the form was found actually. We must check this. Apply this suggestion
```suggestion
if (!form) return {};
```

2024-04-17 16:14 UTC, libattistella commented on apps/web/app/[lang]/studies/[id]/helpers.ts
> +    typeformId: typeformId,
```suggestion
    typeformId,
```

2024-04-17 16:14 UTC, libattistella commented on apps/web/app/[lang]/studies/[id]/helpers.ts
> +    label: label,
```suggestion
    label,
```

2024-04-17 18:06 UTC, jbianciotto commented
> The component is not responding in mobile. It can't be closed neither start the journey
This may be an issue with Chrome developer tools.
I tested on physical devices ( chromie in iPhoneX, chrome in Redmi Note 8, MI browser in Redmi Note 8)  and had no issues with the typeform

2024-04-17 18:36 UTC, libattistella approved these changes

2024-04-17 18:36 UTC, merged