FE-253 Study country
francodimasi/uepm-front-react pull request #177
Opened 2024-04-19 20:53 UTC by jbianciotto

# Description

Choose country when applying to a study, so we can show the correct typeform 

# Jira tickets

https://trialtech.atlassian.net/browse/FE-253

# Screenshots

![image](https://github.com/francodimasi/uepm-front-react/assets/1674845/16ce92d0-15a7-411a-ad95-3956f9213309)
![image](https://github.com/francodimasi/uepm-front-react/assets/1674845/b2d19596-db97-443c-a9ec-e34f2f8d7ed5)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue) :bug:
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) :bomb::boom:
- [ ] Configuration / Setup :wrench:
- [ ] Clean up / Technical debt :hammer:

## Apps affected by this change

- [x] Web
- [ ] Landing
- [ ] Management portal

## Project code modified by this change

- [X] Web
- [ ] Landing
- [ ] Management portal
- [X] Packages

# Checklist:

- [X] I have performed a self-review of my own code :innocent:
- [X] I have tested my change in both resolutions, desktop :computer: and mobile :iphone:
- [X] My code is clean and it follows the guidelines of this project :nail_care:
- [X] My changes don't generate new warnings :ok_hand:

2024-04-20 17:53 UTC, libattistella requested changes

2024-04-20 17:53 UTC, libattistella commented on apps/web/app/[lang]/studies/[id]/components/StudyApplyContent.tsx
> +  const t = useTranslations('studies.studyDetail.preview');
unless you need to pass the translation funtion as a prop to a child component, please combine `t`, `tStudyTypes` and `tGender` into one. you can just have  `const t = useTranslations('studies.studyDetail');` and then just add the remaining path when you call the function.

Ex: `{t('type')}` -> `{t('preview.type')}`

2024-04-20 17:53 UTC, libattistella commented on apps/web/app/[lang]/studies/[id]/components/StudyApplyContent.tsx
> +  const [typeformProps, setTypeformProps] = useState<{
Export this type to have the definition inside the `useState`

2024-04-20 17:53 UTC, libattistella commented on apps/web/app/[lang]/studies/[id]/components/StudyApplyContent.tsx
> +    const typeformIds = getTypeformIds(study, campaignIdParam, countryIdParam);
I think this function is meant to return just one form. Rename it to singular. Ex: `getForm`

2024-04-20 17:53 UTC, libattistella commented on apps/web/app/[lang]/studies/[id]/components/StudyApplyContent.tsx
> +    if (typeformIds) {
```suggestion
    if (form) {
```

2024-04-20 17:53 UTC, libattistella commented on apps/web/app/[lang]/studies/[id]/components/StudyApplyContent.tsx
> +        setTypeformProps({
Why are we setting typeform data before country selection?

2024-04-20 17:53 UTC, libattistella commented on apps/web/app/[lang]/studies/[id]/components/StudyApplyContent.tsx
> +  const [typeformProps, setTypeformProps] = useState<{
```suggestion
  const [typeformData, setTypeformData] = useState<{
```

We use "Props" to define component properties type

2024-04-20 17:53 UTC, libattistella commented on apps/web/app/[lang]/studies/[id]/components/StudyApplyContent.tsx
> +  const countryItems = study.forms.map((form) => {
useMemo

2024-04-20 17:53 UTC, libattistella commented on apps/web/app/[lang]/studies/[id]/components/StudyApplyContent.tsx
>    const ageRequirements = AgeToText(
```suggestion
  const ageRequirements = ageToText(
```

2024-04-20 17:53 UTC, libattistella commented on apps/web/app/[lang]/studies/[id]/components/StudyApplyContent.tsx
>    const typeformHidden = {
useMemo

2024-04-20 17:53 UTC, libattistella commented on apps/web/app/[lang]/studies/[id]/components/StudyApplyContent.tsx
> +      {' '}
Remove

2024-04-20 17:53 UTC, libattistella commented on apps/web/app/[lang]/studies/[id]/components/StudyApplyContent.tsx
> +      {loading ? (
Took this out of the return statement and before return add:

```
if (loading) {
  return <StudyApplyContentSkeleton />
}
```

Then you just return the normal JSX

2024-04-20 17:53 UTC, libattistella commented on apps/web/app/[lang]/studies/[id]/components/StudyEligibility.tsx
> +import { AgeToText } from '../helpers';
```suggestion
import { ageToText } from '../helpers';
```

Functions starts with lowercase

2024-04-20 17:53 UTC, libattistella commented on apps/web/app/[lang]/studies/[id]/components/StudyEligibility.tsx
>    const t = useTranslations('studies.studyDetail.studyEligibility');
Same as before, combine if their not sent as a children component prop

2024-04-20 17:53 UTC, libattistella commented on packages/ui/core/radioGroup/RadioGroup.tsx
> +import NextImage from 'next/image';
Maybe is this one the reason why the flags take too long to load. Try with a common `<img>`

2024-04-20 17:53 UTC, libattistella commented on packages/ui/core/radioGroup/RadioGroup.tsx
> +                          ? 'ring-2 ring-primary'
```suggestion
                          ? `ring-2 ring-${accent}`
```

2024-04-22 06:49 UTC, libattistella commented on apps/web/app/[lang]/studies/[id]/components/StudyApplyContent.tsx
>    const ageRequirements = AgeToText(
Already fixed in mi last [PR](https://github.com/francodimasi/uepm-front-react/pull/182/files#diff-af2a5dfa7d9acf1ffb566528f2f9e57a9805f568f084e78f8454d1833144684b)

2024-04-22 06:52 UTC, libattistella commented on apps/web/app/[lang]/studies/[id]/components/StudyEligibility.tsx
> +import { AgeToText } from '../helpers';
Already fixed in mi last [PR](https://github.com/francodimasi/uepm-front-react/pull/182/files#diff-af2a5dfa7d9acf1ffb566528f2f9e57a9805f568f084e78f8454d1833144684b)

2024-04-22 06:53 UTC, libattistella commented on apps/web/app/[lang]/studies/[id]/components/StudyEligibility.tsx
>    const t = useTranslations('studies.studyDetail.studyEligibility');
Already fixed in mi last [PR](https://github.com/francodimasi/uepm-front-react/pull/182/files#diff-af2a5dfa7d9acf1ffb566528f2f9e57a9805f568f084e78f8454d1833144684b)

2024-04-22 06:58 UTC, libattistella requested changes
A few things

2024-04-22 18:23 UTC, jbianciotto commented on apps/web/app/[lang]/studies/[id]/components/StudyApplyContent.tsx
> +        setTypeformProps({
To select the first country as default, but will remove it

2024-04-22 19:58 UTC, libattistella approved these changes

2024-04-22 19:59 UTC, merged