FE-339  Fetch campaigns from API
francodimasi/uepm-front-react pull request #232
Opened 2024-05-07 18:35 UTC by jbianciotto

# Description

Removed the campaigns json mock and retrieve them from backend API

# Jira tickets

https://trialtech.atlassian.net/browse/FE-339

# Screenshots

If you think a screenshot would be helpful to show this change, please attach it here :grin:

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue) :bug:
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) :bomb::boom:
- [ ] Configuration / Setup :wrench:
- [ ] Clean up / Technical debt :hammer:

## Apps affected by this change

- [x] Web
- [ ] Landing
- [ ] Management portal

## Project code modified by this change

- [ ] Web
- [ ] Landing
- [ ] Management portal
- [ ] Packages

# Checklist:

- [ ] I have performed a self-review of my own code :innocent:
- [ ] I have tested my change in both resolutions, desktop :computer: and mobile :iphone:
- [ ] My code is clean and it follows the guidelines of this project :nail_care:
- [ ] My changes don't generate new warnings :ok_hand:

2024-05-07 19:28 UTC, libattistella requested changes

2024-05-07 19:28 UTC, libattistella commented on apps/web/app/[lang]/components/campaigns/Campaign.tsx
> +        text={tag || String.fromCharCode(160)} //160 = &nbsp;
Why this?

2024-05-07 19:28 UTC, libattistella commented on apps/web/api/campaigns/requests.ts
> +      link: `${process.env.NEXT_PUBLIC_DOMAIN}/ensayo-clinico/${campaign.id}`,
I think we can star using the new url (studies/...), in some point we will stop using a middleware redirection

2024-05-07 19:28 UTC, libattistella commented on apps/web/api/campaigns/requests.ts
> +  if (data.total_pages > 1) {
Remove for now please

2024-05-07 19:32 UTC, jbianciotto commented on apps/web/api/campaigns/requests.ts
> +  if (data.total_pages > 1) {
Wouldnt it be nice to have someway to detect when we are returning more results and need adding the next pages consumption?

2024-05-07 19:33 UTC, jbianciotto commented on apps/web/app/[lang]/components/campaigns/Campaign.tsx
> +        text={tag || String.fromCharCode(160)} //160 = &nbsp;
If tag is empty campaigns wont show up aligned, that is why I added the blank space to reserve the space and dont break the layout

2024-05-07 19:34 UTC, jbianciotto commented on apps/web/api/campaigns/requests.ts
> +      link: `${process.env.NEXT_PUBLIC_DOMAIN}/ensayo-clinico/${campaign.id}`,
I dont understand. Instead of /ensayo-clinico/ it should be /studies/ ?

2024-05-08 06:34 UTC, libattistella commented on apps/web/api/campaigns/requests.ts
> +      link: `${process.env.NEXT_PUBLIC_DOMAIN}/ensayo-clinico/${campaign.id}`,
Yep, `/ensayo-clinico/` is part of an url that belongs to the old site. As you may know, we don't have that path segment as part of our studies in this project. For compatibility with the old site, and the campaigns urls going around social networks, etc, we have added a middleware redirection. But the real url for our futures campaign will be `/studies/[id]?campaign_id=[cid]`

2024-05-08 06:38 UTC, libattistella commented on apps/web/api/campaigns/requests.ts
> +  if (data.total_pages > 1) {
Is not something that we will be happening in the near future, neither an error, and we will add a pagination mechanism here in some point. Is part of tech debt

2024-05-08 06:40 UTC, libattistella commented on apps/web/app/[lang]/components/campaigns/Campaign.tsx
> +        text={tag || String.fromCharCode(160)} //160 = &nbsp;
Ok, please add a screenshot to see what you mean. Are you planning handle the case where a tag is longer and takes two lines?

2024-05-08 15:52 UTC, jbianciotto commented on apps/web/api/campaigns/requests.ts
> +      link: `${process.env.NEXT_PUBLIC_DOMAIN}/ensayo-clinico/${campaign.id}`,
endpoint will be /studies/[id], we dont have campaing_id in the data response

2024-05-08 16:29 UTC, libattistella requested changes

2024-05-08 16:29 UTC, libattistella commented on apps/web/api/endpoints.ts
> +  STUDIES_INDEX: `${BASE_URL}/studies/reduced_index`,
```suggestion
  ACTIVE_STUDIES: `${BASE_URL}/studies/reduced_index`,
```

2024-05-08 17:51 UTC, libattistella requested changes

2024-05-08 17:51 UTC, libattistella commented on apps/web/app/[lang]/components/campaigns/Campaigns.types.ts
>  export type CampaignProps = {
export type CampaignProps = LolacaProps & { ... }

2024-05-08 17:51 UTC, libattistella commented on apps/web/app/[lang]/components/campaigns/Campaigns.types.ts
> +  locale: string;
Use `LocaleProps` type

2024-05-08 17:51 UTC, libattistella commented on apps/web/app/[lang]/components/campaigns/Campaigns.types.ts
> +  locale: string;
Use `LocaleProps` type

2024-05-08 18:05 UTC, libattistella approved these changes

2024-05-08 18:06 UTC, merged