FE-352 Back button component
francodimasi/uepm-front-react pull request #237
Opened 2024-05-09 17:20 UTC by jbianciotto

# Description

Use browser back instead of hardcoding back links in pages.
Created a BackButton component to reuse through the project

# Jira tickets
https://trialtech.atlassian.net/browse/FE-352

# Screenshots

If you think a screenshot would be helpful to show this change, please attach it here :grin:

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue) :bug:
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) :bomb::boom:
- [ ] Configuration / Setup :wrench:
- [ ] Clean up / Technical debt :hammer:

## Apps affected by this change

- [x] Web
- [ ] Landing
- [ ] Management portal

## Project code modified by this change

- [ ] Web
- [ ] Landing
- [ ] Management portal
- [ ] Packages

# Checklist:

- [ ] I have performed a self-review of my own code :innocent:
- [ ] I have tested my change in both resolutions, desktop :computer: and mobile :iphone:
- [ ] My code is clean and it follows the guidelines of this project :nail_care:
- [ ] My changes don't generate new warnings :ok_hand:

2024-05-09 19:15 UTC, libattistella requested changes

2024-05-09 19:15 UTC, libattistella commented on apps/web/app/[lang]/blog/article/[slug]/components/ArticleTitle.tsx
> +        <BackButton>
Since this is not a ui component from packages and will only be used in this project, I think we can safely move the `ArrowBackIcon` component inside the `BackButton` and just have <BackButton /> wherever we want to use it

2024-05-09 19:20 UTC, libattistella requested changes

2024-05-09 19:20 UTC, libattistella commented on apps/web/components/utils/BackButton.tsx
> +}: React.PropsWithChildren<{
`PropsWithClassname` already inludes `PropsWithChildren`. Use that one directly.

2024-05-09 19:20 UTC, libattistella commented on apps/web/components/utils/BackButton.tsx
> +export const BackButton = ({
It would be nice to have a fallback prop, that will receive a url to navigate is there is no page to go back. So it will behave as it is right now in that case.

You can take a look on how this is implemented here: https://ionicframework.com/docs/api/back-button

2024-05-10 11:01 UTC, libattistella requested changes

2024-05-10 13:27 UTC, jbianciotto commented on apps/web/app/[lang]/components/stories/Stories.tsx
> +            className="hidden 2xl:flex w-32 h-64 opacity-80"
I did check it, the conflicting classes were added in this commit
https://github.com/francodimasi/uepm-front-react/commit/da22e90172817e0d4e52403c917bab7e23f97b64#
I tried to guess the logic behind that change and accomodate to this code, but I am fine with your suggested code anyway

2024-05-10 13:50 UTC, libattistella approved these changes

2024-05-10 13:54 UTC, merged