FE-372 Sponsors landing page: Channels (section 3)
francodimasi/uepm-front-react pull request #282
Opened 2024-06-07 20:42 UTC by jbianciotto

TODO: links, contactUs CTA

# Description
FE-372, section 3 (channels) for sponsors landing page
# Jira tickets
https://trialtech.atlassian.net/browse/FE-372
# Screenshots

If you think a screenshot would be helpful to show this change, please attach it here :grin:

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue) :bug:
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) :bomb::boom:
- [ ] Configuration / Setup :wrench:
- [ ] Clean up / Technical debt :hammer:

## Apps affected by this change

- [x] Web
- [ ] Landing
- [ ] Management portal

## Project code modified by this change

- [ ] Web
- [ ] Landing
- [ ] Management portal
- [ ] Packages

# Checklist:

- [ ] I have performed a self-review of my own code :innocent:
- [ ] I have tested my change in both resolutions, desktop :computer: and mobile :iphone:
- [ ] My code is clean and it follows the guidelines of this project :nail_care:
- [ ] My changes don't generate new warnings :ok_hand:

2024-06-10 06:18 UTC, libattistella requested changes

2024-06-10 16:05 UTC, jbianciotto commented on packages/ui/core/typography/P1.tsx
> +  className='',
if you dont pass className, you get 'undefined' classes added in the html

2024-06-12 10:09 UTC, libattistella requested changes

2024-06-12 10:09 UTC, libattistella commented on apps/web/app/[lang]/sponsors/components/About.tsx
Remove padding top for mobile

![pt](https://github.com/francodimasi/uepm-front-react/assets/17297888/ae80a1f6-7ab6-4ae2-b7a5-a27e8a3bb69a)

2024-06-12 17:02 UTC, libattistella approved these changes

2024-06-12 17:24 UTC, merged