FE-367 Contact us form, remaining sections in sponsors landing page
francodimasi/uepm-front-react pull request #286
Opened 2024-06-12 20:34 UTC by jbianciotto

# Description
Sponsors landing page

# Jira tickets
https://trialtech.atlassian.net/browse/FE-371
https://trialtech.atlassian.net/browse/FE-373
https://trialtech.atlassian.net/browse/FE-374

# Screenshots

If you think a screenshot would be helpful to show this change, please attach it here :grin:

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue) :bug:
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) :bomb::boom:
- [ ] Configuration / Setup :wrench:
- [ ] Clean up / Technical debt :hammer:

## Apps affected by this change

- [x] Web
- [ ] Landing
- [ ] Management portal

## Project code modified by this change

- [ ] Web
- [ ] Landing
- [ ] Management portal
- [ ] Packages

# Checklist:

- [ ] I have performed a self-review of my own code :innocent:
- [ ] I have tested my change in both resolutions, desktop :computer: and mobile :iphone:
- [ ] My code is clean and it follows the guidelines of this project :nail_care:
- [ ] My changes don't generate new warnings :ok_hand:

2024-06-13 18:43 UTC, libattistella requested changes
Nice job

2024-06-13 18:43 UTC, libattistella commented on apps/web/.env.development
> -# NEXT_PUBLIC_PRODUCT_SPONSORS=https://preview.trialtech.es/
Aren't we redirecting the user to the physician's site from the landing?

2024-06-13 18:43 UTC, libattistella commented on apps/web/.env.production
> -# NEXT_PUBLIC_PRODUCT_SPONSORS=https://preview.trialtech.es/
Same as before

2024-06-13 18:43 UTC, libattistella commented on apps/web/app/[lang]/components/main/MainLinks.tsx
> +      <Link href={`/${locale}/sponsors`} target="_blank" className="flex-1">
Use `intl/navigation` Link for navigates inside the app and pass locale as prop

`import { Link } from '@intl/navigation';`

2024-06-13 18:43 UTC, libattistella commented on apps/web/components/shared/contactUs/ContactUsForm.tsx
> +        const updatedData = data;
```suggestion
        const updatedData = { ...data };
```

2024-06-13 18:43 UTC, libattistella commented on apps/web/components/shared/contactUs/ContactUsForm.tsx
> +        const updatedData = data;
Also, it would be fine to have this logic in a helper file, and have something like this:
```
try {
  await formSenderFn(parseData(data));
  setSent(true);
}
```

2024-06-13 18:43 UTC, libattistella commented on apps/web/components/shared/contactUs/ContactUsForm.tsx
>          console.log(error);
This will log into the browser console. Remove please

2024-06-13 18:43 UTC, libattistella commented on apps/web/components/shared/contactUs/ContactUs.types.ts
> +  [key: string]: {
```suggestion
  [key: 'name' | 'lastname' | 'email' | 'role' | 'query' | 'phone']: {
```
In this way, then you can use dot notation in the form.

2024-06-13 18:43 UTC, libattistella commented on apps/web/components/shared/contactUs/ContactUsForm.tsx
> +              {!hiddenFields['role'] && (
Applying the change mentioned on the types, you should be able to use dot notation here

`!hiddenFields.role`

2024-06-13 18:43 UTC, libattistella commented on apps/web/components/shared/contactUs/ContactUsForm.tsx
> +              {!hiddenFields['role'] && (
Also, please add this conditional to **_all_** fields

2024-06-13 18:43 UTC, libattistella commented on apps/web/app/[lang]/sponsors/components/Contact.tsx
> +                Sabrina Brignardello
Regardless if this has translations or not, it should be in the translations files with the same value for all languages. Same applies for any text here

2024-06-13 20:47 UTC, jbianciotto commented on apps/web/.env.development
> -# NEXT_PUBLIC_PRODUCT_SPONSORS=https://preview.trialtech.es/
We do have a different env var NEXT_PUBLIC_PRODUCT_PHYSICIANS for physicians
This one I removed was commented, is replaced by our /sponsors page

2024-06-14 06:32 UTC, libattistella commented on apps/web/.env.development
> -# NEXT_PUBLIC_PRODUCT_SPONSORS=https://preview.trialtech.es/
Yes, I messed up sponsors with physicians, but we don't have any extra product for sponsors

2024-06-14 06:40 UTC, libattistella requested changes

2024-06-14 06:40 UTC, libattistella commented on apps/web/app/[lang]/components/main/MainLinks.tsx
> +      <LinkIntl href={'/sponsors'} target="_blank" className="flex-1">
```suggestion
      <LinkIntl href={'/sponsors'} locale={locale} target="_blank" className="flex-1">
```

2024-06-18 18:46 UTC, libattistella approved these changes

2024-06-18 18:48 UTC, merged