Feature/fe 15 post details
francodimasi/uepm-front-react pull request #46
Opened 2023-12-15 15:51 UTC by jbianciotto

# Description

Please include a summary of your changes.

# Jira tickets

Please include a list with the tickets involved in this pull request :pray:

- [FE-### | Title]([link])

# Screenshots

If you think a screenshot would be helpful to show this change, please attach it here :grin: 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue) :bug:
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) :bomb::boom:
- [ ] Configuration / Setup :wrench:
- [ ] Clean up / Technical debt :hammer:

## Apps affected by this change

- [X] Web
- [ ] Landing
- [ ] Management portal

## Project code modified by this change

- [ ] Web
- [ ] Landing
- [ ] Management portal
- [ ] Packages

# Checklist:

- [X] I have performed a self-review of my own code :innocent:
- [] My code is clean  and it follows the guidelines of this project :nail_care:
- [ ] My changes don't generate new warnings :ok_hand:

2023-12-18 11:44 UTC, libattistella requested changes

2023-12-18 15:36 UTC, jbianciotto commented on apps/web/api/blog/types/blog.types.ts
> +  tags?: number[];
BlogPost is used for responses from WP. Tags come as strings there. However, when making a request you must provide them as an integer array of ids

2023-12-18 18:16 UTC, jbianciotto commented on apps/web/api/blog/useBlog.ts
> +    const res = await fetch(
This will probably be modified by lmartinez PR, I will hold on until that one is merged to review this

2023-12-19 11:28 UTC, libattistella commented on apps/web/api/blog/types/yoast.types.ts
> +  "Escrito por": string;
So this is something defined by us probably. I will check with Franco first

2023-12-19 11:29 UTC, libattistella commented on apps/web/api/blog/useBlog.ts
> +    const res = await fetch(
Ok then. FYI @lsmartinez88

2023-12-19 11:33 UTC, libattistella requested changes

2023-12-19 13:45 UTC, jbianciotto commented on apps/web/package.json
> +    "@types/react": "^18.2.8",
Same as typescript version bump, was having issues when building async Server Components. Google search led me to this [https://stackoverflow.com/questions/72668405/promiseelement-is-not-a-valid-jsx-element-converting-promiseelement-to-elem](https://stackoverflow.com/questions/72668405/promiseelement-is-not-a-valid-jsx-element-converting-promiseelement-to-elem), but I am testing it again to confirm if it is really needed or not

2023-12-20 13:24 UTC, libattistella requested changes

2023-12-20 13:24 UTC, libattistella commented on apps/web/app/[lang]/blog/article/[slug]/components/ArticleTags.tsx
> +                { articleTags.map((tag, index) => (
Please add the `?` operator on every map if you are not defining a default value for the array. 
The fact that this is required will only control that we are not sending a possible undefined value on our own or we forget to pass the prop, but won't prevent the component from receive an undefined value.

2023-12-20 13:24 UTC, libattistella commented on apps/web/app/[lang]/blog/article/[slug]/components/ArticleTags.tsx
> +                { articleTags.map((tag, index) => (
```suggestion
                { articleTags?.map((tag, index) => (
```

2023-12-20 13:24 UTC, libattistella commented on apps/web/app/[lang]/blog/article/[slug]/components/Interesting.tsx
> +            { blogPost && <div className="pb-6 border-b border-gray-medium flex-col justify-start items-start gap-8 inline-flex">
Please check for blogPost first and return null if there is no value.
```suggestion
            if (!blogPost) return null;
            <div className="pb-6 border-b border-gray-medium flex-col justify-start items-start gap-8 inline-flex">
```

2023-12-20 13:24 UTC, libattistella commented on apps/web/app/[lang]/blog/article/[slug]/page.tsx
> +    const recommendedPosts = await getPostListFn(getPostsParams)
Please make sure that all the getter functions for the blog return a value in the catch block to handle this case.

You can let this too if you don't use this constant for anything else:
```suggestion
    return await getPostListFn(getPostsParams)
```

2023-12-20 13:24 UTC, libattistella commented on apps/web/app/[lang]/blog/article/[slug]/page.tsx
> +    const response = await fetch (`${ENDPOINTS.BLOG.POSTS}${queryParams}`,{
Add a try/catch block please

2023-12-20 14:05 UTC, jbianciotto commented on apps/web/package.json
> +    "@types/react": "^18.2.8",
I reverted this, it looks like is not need

2023-12-20 14:24 UTC, jbianciotto commented on apps/web/app/[lang]/blog/article/[slug]/Article.types.ts
> +    params: {slug: string}
Yes, 'params' argument comes from generateStaticParams to populate the [slug] dynamic segment

2023-12-20 19:05 UTC, libattistella requested changes

2023-12-20 19:05 UTC, libattistella commented on apps/web/public/images/Arrow 1.svg
Please remove this. This should be using the `ArrowBackIcon` component that @lsmartinez88 will create. For now you can use another icon of the `ui/core/icons` package

2023-12-20 19:05 UTC, libattistella commented on apps/web/public/images/search-normal.svg
Please remove this. Create a `ShareOutlineIcon` in the `ui/core/icons` package

2023-12-20 19:05 UTC, libattistella commented on apps/web/public/images/Ellipse 1.svg
Please remove this. Create an `EllipsisIcon` in the ui/core/icons package

2023-12-21 19:41 UTC, libattistella requested changes

2023-12-21 19:41 UTC, libattistella commented on packages/ui/core/icons/ArrowBackIcon.svg
Please create the correspondent component. You can take a look on `packages\ui\core\icons\CloseIcon.tsx`

2023-12-21 19:41 UTC, libattistella commented on packages/ui/core/icons/EllipsisIcon.svg
Please create the correspondent component. You can take a look on `packages\ui\core\icons\CloseIcon.tsx`

2023-12-21 19:41 UTC, libattistella commented on packages/ui/core/icons/ShareOutlineIcon.svg
Please create the correspondent component. You can take a look on `packages\ui\core\icons\CloseIcon.tsx`

2023-12-21 19:41 UTC, libattistella commented on .husky/pre-commit
Remove this file from the PR. I don't know why is empty. But you should get the correct one pulling from develop

2023-12-28 16:22 UTC, libattistella approved these changes

2023-12-28 16:23 UTC, merged