arbitrary order for blog categories
francodimasi/uepm-front-react pull request #67
Opened 2024-01-04 15:58 UTC by jbianciotto

# Description

Created function to set an arbitrary order to the list of blog categories

# Jira tickets

Please include a list with the tickets involved in this pull request :pray:
[
- [FE-### | Title]([link])](https://trialtech.atlassian.net/browse/FE-142)

# Screenshots

If you think a screenshot would be helpful to show this change, please attach it here :grin:

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue) :bug:
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) :bomb::boom:
- [ ] Configuration / Setup :wrench:
- [ ] Clean up / Technical debt :hammer:

## Apps affected by this change

- [x] Web
- [ ] Landing
- [ ] Management portal

## Project code modified by this change

- [X] Web
- [ ] Landing
- [ ] Management portal
- [ ] Packages

# Checklist:

- [X] I have performed a self-review of my own code :innocent:
- [ ] My code is clean and it follows the guidelines of this project :nail_care:
- [X] My changes don't generate new warnings :ok_hand:

2024-01-04 17:32 UTC, libattistella requested changes

2024-01-04 17:32 UTC, libattistella commented on apps/web/helpers/category_helpers.ts
> +const CATEGORIES_ORDER = new Map([
Why not use the IDs? We could be receiving translated categories in the next future?

2024-01-04 17:32 UTC, libattistella commented on apps/web/helpers/category_helpers.ts
> +  ['DEFAULT', 5],
What is default?

2024-01-04 17:46 UTC, jbianciotto commented on apps/web/helpers/category_helpers.ts
> +  ['DEFAULT', 5],
I use that DEFAULT value as the highest one, to make any category not in the list,  go at the end

2024-01-04 17:47 UTC, jbianciotto commented on apps/web/helpers/category_helpers.ts
> +const CATEGORIES_ORDER = new Map([
I used the slug as a kind of ID

2024-01-04 18:16 UTC, libattistella commented on apps/web/helpers/category_helpers.ts
> +const CATEGORIES_ORDER = new Map([
Yes, we should use the id, the slug could be even changing depending on how the guys resolve things on wordpress

2024-01-04 18:18 UTC, libattistella commented on apps/web/helpers/category_helpers.ts
> +  ['DEFAULT', 5],
I see, but what if instead of send them at the end of the line, we just remove any tag that doesn't match the expected ones? We order the tags we are expecting and remove any other present in the array

2024-01-05 07:39 UTC, libattistella approved these changes

2024-01-05 07:39 UTC, merged